// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LAPTemplateMVC.Models;
using LAPTemplateMVC.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LAPTemplateMVC.Models.Configurations
{
    public partial class AusgabeConfiguration : IEntityTypeConfiguration<Ausgabe>
    {
        public void Configure(EntityTypeBuilder<Ausgabe> entity)
        {
            entity.ToTable("AUSGABE", tb =>
                {
                    tb.HasTrigger("TRG_AD_AUSGABE");
                    tb.HasTrigger("TRG_AI_AUSGABE");
                    tb.HasTrigger("TRG_AU_AUSGABE");
                    tb.HasTrigger("TRG_BD_AUSGABE");
                    tb.HasTrigger("TRG_BI_AUSGABE");
                    tb.HasTrigger("TRG_BU_AUSGABE");
                });

            entity.Property(e => e.Valid).HasDefaultValue((short)1);

            entity.HasOne(d => d.Kategorie).WithMany(p => p.Ausgabe)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AUSGABE_KATEGORIE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Ausgabe> entity);
    }
}
