// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LAPTemplateMVC.Models;
using LAPTemplateMVC.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LAPTemplateMVC.Models.Configurations
{
    public partial class KategorieConfiguration : IEntityTypeConfiguration<Kategorie>
    {
        public void Configure(EntityTypeBuilder<Kategorie> entity)
        {
            entity.ToTable("KATEGORIE", tb =>
                {
                    tb.HasTrigger("TRG_AD_KATEGORIE");
                    tb.HasTrigger("TRG_AI_KATEGORIE");
                    tb.HasTrigger("TRG_AU_KATEGORIE");
                    tb.HasTrigger("TRG_BD_KATEGORIE");
                    tb.HasTrigger("TRG_BI_KATEGORIE");
                    tb.HasTrigger("TRG_BU_KATEGORIE");
                });

            entity.Property(e => e.Valid).HasDefaultValue((short)1);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Kategorie> entity);
    }
}
