// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LAPTemplateMVC.Models.dboSchema
{
    public partial class AusgabeGetByKategorieIDResult
    {
        public long AusgabeID { get; set; }
        public long KATEGORIEID { get; set; }
        public string BEZEICHNUNG { get; set; }
        [Column("BETRAG", TypeName = "decimal(10,2)")]
        public decimal BETRAG { get; set; }
        public short VALID { get; set; }
        public string MOD_USER { get; set; }
        public DateTime MOD_TIMESTAMP { get; set; }
        public string CR_USER { get; set; }
        public DateTime CR_TIMESTAMP { get; set; }
    }
}
