// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using LAPTemplateMVC.Models.dboSchema;


namespace LAPTemplateMVC.Models.dboSchema;

[Table("EINNAHME")]
[Index("Valid", Name = "IX_EINNAHME_VALID", AllDescending = true)]
public partial class Einnahme
{
    [Key]
    [Column("EINNAHMEID")]
    public long Einnahmeid { get; set; }

    [Column("KATEGORIEID")]
    public long Kategorieid { get; set; }

    [Required]
    [Column("BEZEICHNUNG")]
    [StringLength(50)]
    public string Bezeichnung { get; set; }

    [Column("BETRAG", TypeName = "decimal(10, 2)")]
    public decimal Betrag { get; set; }

    [Column("VALID")]
    public short Valid { get; set; }

    [Required]
    [Column("MOD_USER")]
    [StringLength(256)]
    public string ModUser { get; set; }

    [Column("MOD_TIMESTAMP", TypeName = "datetime")]
    public DateTime ModTimestamp { get; set; }

    [Required]
    [Column("CR_USER")]
    [StringLength(256)]
    public string CrUser { get; set; }

    [Column("CR_TIMESTAMP", TypeName = "datetime")]
    public DateTime CrTimestamp { get; set; }

    [ForeignKey("Kategorieid")]
    [InverseProperty("Einnahme")]
    public virtual Kategorie Kategorie { get; set; }
}